# Generated by Django 3.0.5 on 2021-04-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('flag', models.TextField()),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Covid_Cases',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
            ],
        ),
    ]
